// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Order struct {
	ID        string        `json:"id"`
	LocalID   string        `json:"localId"`
	LocalName string        `json:"localName"`
	Payment   *OrderPayment `json:"payment"`
	Address   *OrderAddress `json:"address"`
}

func (Order) IsEntity() {}

type OrderPayment struct {
	ID            string  `json:"id"`
	PaymentMethod *string `json:"paymentMethod"`
}
